name: release
on:
  push:
    branches:
      - trunk
    paths:
      - Dockerfile
  schedule:
    - cron: '10 16 * * 2'
  repository_dispatch:
    types: [release]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set tag
        id: step_one
        run: |
          echo "docker_tag=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: cache buildx
        uses: actions/cache@v2.1.7
        with:
          path: ~/.buildx
          key: ${{ runner.os }}-node-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: build
        run: >-
          docker buildx build
          --cache-from type=local,src=$HOME/.buildx
          --cache-to   type=local,dest=$HOME/.buildx,mode=max
          --platform linux/amd64,linux/arm64/v8
          --tag ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ env.docker_tag }}
          --push .
