name: test
on:
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

